### PR TITLE
Make the tooltip focusable

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/19783

*Description of changes:*
- Make the tooltip focusable and add cypress tests
- Uncomment cypress tests for expanded form (covering AA tests in https://github.com/bcgov/entity/issues/19441)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-129-x0krc4xb.web.app

**Comment by kialj876** [comment]
nice work 👍 

Is there an accessibility test to uncomment for this? If not can you secure it with one?

**Comment by patrickpeinanw** [comment]
> nice work 👍
> 
> Is there an accessibility test to uncomment for this? If not can you secure it with one?

No, we don't have a cypress test for this. I'll add one.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-129-x0krc4xb.web.app

**Review by kialj876 — APPROVED** [review]
nice work!

**Pull request merged**
