### PR TITLE
17982 - Fixed issue happing after change of event type from change to keydown.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:17982*https://github.com/bcgov/entity/issues/17982

*Description of changes:*
- Fixed issue happing after change of event type from change to keydown.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-65-yb14zaqc.web.app

**Comment by kialj876** [comment]
just needs the lint fix

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-65-yb14zaqc.web.app

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
