### PR TITLE
Update how the "help" section opens/closes

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/21069

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-158-6ybinukn.web.app

**Review by hfekete — APPROVED** [review]

**Review by kialj876 — APPROVED** [review]
Looks good but can you update 'Help with significant individuals' before merging?

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-158-6ybinukn.web.app

**Pull request merged**
