### PR TITLE
Fix failing unit tests after Vitest upgrade

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/20310

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-144-6v9yuqzq.web.app

**Review by kialj876 — APPROVED** [review]
Nice so was the issue just how the axios mock was getting exported?

**Comment by patrickpeinanw** [comment]
> Nice so was the issue just how the axios mock was getting exported?

Yeah. That was the main issue. The error message is "SyntaxError: Cannot export hoisted variable. You can control hoisting behavior by placing the import from this file first."

Another failure occurred at 
```
expect(axiosRequestMocks.get).toHaveBeenCalledWith(
    `https://legal-api-dev.apps.silver.devops.gov.bc.ca/api/v2/businesses/${testBusinessBEN.business.identifier}`,
    { params: { slim: true } }
)`
```
The expected url is `"https://legal-api-dev.apps.silver.devops.gov.bc.ca/api/v2/businesses/BC0871427"` while the actual url is `"/businesses/BC0871427"` . It is because `useRuntimeConfig().public.legalApiURL` returns an empty string.  
(I just realized that my solution is just bypassing this issue instead of solving it )

**Pull request merged**
