### PR TITLE
Align radio top, display exteranl influence in any case.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:18668*https://github.com/bcgov/entity/issues/18668

*Description of changes:*
- ux changes for 18668
  - aligning radios to top
  - displaying "external influence" info always in summary table

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-113-8aduxi5s.web.app

**Comment by J-Baese** [comment]
Small thing, but it seems like it's sitting higher than the checkbox component? If we can bump it down a couple of pixels to match where the checkboxes sit that would be ideal. Thanks!

**Review by J-Baese — CHANGES_REQUESTED** [review]
Small thing, but it seems like it's sitting higher than the checkbox component? If we can bump it down a couple of pixels to match where the checkboxes sit that would be ideal. Thanks!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-113-8aduxi5s.web.app

**Comment by J-Baese** [comment]
Looks good thanks1

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
