### PR TITLE
21055 - No significant individual submission

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:21055 *https://github.com/bcgov/entity/issues/21055 

*Description of changes:*
- fixed the issue where you could not submit due to no significant individuals on page (even with checkbox selected)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-156-27zxzrvi.web.app

**Review by kialj876 — APPROVED** [review]
Nice

**Pull request merged**
