### PR TITLE
18327 - adding tests and updated sytles

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:18327*https://github.com/bcgov/entity/issues/18327

*Description of changes:*
- added some tests 
- added component to the main page in main app
- added regions for dropdown

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-38-0zgnzelr.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-38-0zgnzelr.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-38-0zgnzelr.web.app

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
