### PR TITLE
Fix country not selected when autocomplete address.

### PR DESCRIPTION
**Pull request by hfekete**
*Description of changes:*
- fixed issue when country was not selected in dropdown when autocompleting address

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-44-jwb3s054.web.app

**Comment by kialj876** [comment]
can you fix the CI? Looks like you just need to do a pnpm install from btr-web to push the package changes to the pnpm-locks

**Comment by hfekete** [comment]
> can you fix the CI? Looks like you just need to do a pnpm install from btr-web to push the package changes to the pnpm-locks. You should also make sure removing the nuxt/test-utils doesn't break the current tests. I think btr-main-app needs it. If it does I think we can remove it from that later and switch everything to cypress

Pushed the lock files too now.
No, btr-main-app should not need it anymore. It has errors, but these are not part of what is tested, it is due to the language lib. 
Will make those error go away in another PR. Need to do bit of copy pasting and making sure its loading proper files in there.

**Comment by kialj876** [comment]
> > can you fix the CI? Looks like you just need to do a pnpm install from btr-web to push the package changes to the pnpm-locks. You should also make sure removing the nuxt/test-utils doesn't break the current tests. I think btr-main-app needs it. If it does I think we can remove it from that later and switch everything to cypress
> 
> Pushed the lock files too now. No, btr-main-app should not need it anymore. It has errors, but these are not part of what is tested, it is due to the language lib. Will make those error go away in another PR. Need to do bit of copy pasting and making sure its loading proper files in there.

I'd rather you keep it in for now as it isn't breaking anything in btr-main-app. Remove it in the PR where you fix it?

**Comment by hfekete** [comment]
> > can you fix the CI? Looks like you just need to do a pnpm install from btr-web to push the package changes to the pnpm-locks. You should also make sure removing the nuxt/test-utils doesn't break the current tests. I think btr-main-app needs it. If it does I think we can remove it from that later and switch everything to cypress
> 
> Pushed the lock files too now. No, btr-main-app should not need it anymore. It has errors, but these are not part of what is tested, it is due to the language lib. Will make those error go away in another PR. Need to do bit of copy pasting and making sure its loading proper files in there.

Actually, I jumped the gun here, it looks like the errors might be due to the not loading .env file for tests.

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
