### PR TITLE
20754 - Indicate if this is your information

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:20754 *https://github.com/bcgov/entity/issues/20754 

*Description of changes:*
- add new section " Indicate if this is your information"
- add name from the account when checkbox selected

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by kialj876 — COMMENTED** [review]
Looks good, but can you add a cypress test to secure this?

I also noticed that for our test account it triggers the validation on 'full name' because there is a '2' in the name so it blocks filing. I don't think we should validate anything on full name if we are getting the value from the account which may have different validation rules than us for names

**Review by patrickpeinanw — COMMENTED** [review]
If someone checks the 'adding my own information' option when adding a person, should they be allowed to check it again when adding another SI?

**Comment by hfekete** [comment]
> Looks good, but can you add a cypress test to secure this?
> 
> I also noticed that for our test account it triggers the validation on 'full name' because there is a '2' in the name so it blocks filing. I don't think we should validate anything on full name if we are getting the value from the account which may have different validation rules than us for names

Finally was able to make validation not trigger when checkbox selected for this specific usecase :P

**Comment by hfekete** [comment]
> If someone checks the 'adding my own information' option when adding a person, should they be allowed to check it again when adding another SI?

I'll leave that we can add this as many times as we wont for now, and we can change this in future, depending on the input from the design.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-150-w83gmqo3.web.app

**Review by patrickpeinanw — APPROVED** [review]
Thanks for the updates!

**Review by kialj876 — APPROVED** [review]
nice!

**Pull request merged**
