### PR TITLE
20839 - Update to summary table; removing external influence.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:20839*https://github.com/bcgov/entity/issues/20839

*Description of changes:*
- removed external influence from Summary Table
- removed external influence from other parts of code
- updated Edit Individual in Summary table to not have multiple levels of titles

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-147-r645s3l4.web.app

**Review by patrickpeinanw — CHANGES_REQUESTED** [review]
Nice work! We just need to update the summaryTable.cy.ts because it now still expects the form to contain "Edit an Individual". 

Another thing: as we break the form into different sections, the space between two sections is really big in the edit form. I am not sure if we need to adjust the style (e.g., remove the space between two sections in the edit mode). It can be a design question.

**Comment by kialj876** [comment]
Nothing to add outside of patrick's review other than I think we agreed not to worry about the edit form mode UX till later so I think you can leave that part it as is. Looks good, just needs the CI fixes

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-147-r645s3l4.web.app

**Comment by hfekete** [comment]
I reverted the edit stuff in summary table, as it will need some input from the designers.

**Review by patrickpeinanw — APPROVED** [review]

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
