### PR TITLE
UI: add Preferred Name component

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/18169

*Description of changes:*
- create Preferred Name component in btr-common-components
- add Preferred Name component to btr-main-app
- update cypress e2e tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by hfekete — APPROVED** [review]
Thanks for updating it to use the same component.

**Review by kialj876 — APPROVED** [review]
Nice work 👍

**Pull request merged**
