### PR TITLE
18794 - Folio or Reference Number.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:18794 *https://github.com/bcgov/entity/issues/18794 

*Description of changes:*
- added folio or reference number item.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-76-0f759sow.web.app

**Review by kialj876 — APPROVED** [review]
👍

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-76-0f759sow.web.app

**Pull request merged**
