### PR TITLE
UX/UI updates for Edit State

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/

*Description of changes:*
- Edit buttons are disabled when the "Add an Individual" form is open
- The right edge of the dropdown "Remove" button is aligned with the right edge of the Edit button
- Font size changing
- Add a dimmed/disabled "Remove" button in the "Add an Individual" form

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-102-q0p924yq.web.app

**Review by kialj876 — APPROVED** [review]
nice work 👍

**Review by hfekete — APPROVED** [review]

**Review by hfekete — APPROVED** [review]
Nice, I had some questions on code that you answered in tests :D

**Pull request merged**
