### PR TITLE
23115 - bugfix for submitting with missing info.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:23115 *https://github.com/bcgov/entity/issues/23115 

*Description of changes:*
properly tracking change for missing info reason

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-195-6gv5d11n.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-195-6gv5d11n.web.app

**Review by BrandonSharratt — APPROVED** [review]
Looks good to me

**Pull request merged**
