### PR TITLE
Fixes and code reorg.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:*https://github.com/bcgov/entity/issues/

*Description of changes:*
- Did some code cleanup
- added guardrail so that new fee cannot be added if there is undefined mandatory data.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-79-6qj8mao3.web.app

**Review by patrickpeinanw — APPROVED** [review]
Looks good to me. 
Some e2e tests failed initially but passed after a manual re-run. It happened to my PRs before

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-79-6qj8mao3.web.app

**Comment by hfekete** [comment]
> Looks good to me. Some e2e tests failed initially but passed after a manual re-run. It happened to my PRs before

Yeah, thanks. I talked with Kial about it the other day, and I we agreed that this cypress stuff needs to be looked at. I guess we will need to spend some more time in next year trying to figure it out.

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
