### PR TITLE
styling tweaks

### PR DESCRIPTION
**Pull request by kialj876**
*Issue:*https://github.com/bcgov/entity/issues/19095

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-91-2kqm0thn.web.app

**Comment by patrickpeinanw** [comment]
The styling tweak in this PR looks good to me. 
But why did we apply "rounded-t-md" to all the input fields?

**Review by hfekete — APPROVED** [review]
Thanks for beautification !
Looks better :D

**Comment by kialj876** [comment]
> The styling tweak in this PR looks good to me. But why did we apply "rounded-t-md" to all the input fields?

haha that is following the look we have across all the other bcgov apps

**Pull request merged**
