### PR TITLE
18959 19094 ldarkly integration plus UI tweak

### PR DESCRIPTION
**Pull request by kialj876**
*Issue:*https://github.com/bcgov/entity/issues/18959
*Issue:*https://github.com/bcgov/entity/issues/19094

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-90-22gn9jqo.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-90-22gn9jqo.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-90-22gn9jqo.web.app

**Review by hfekete — APPROVED** [review]
Good work!

**Pull request merged**
