### PR TITLE
19105 - schema conversion on submit data

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:19105*https://github.com/bcgov/entity/issues/19105

*Description of changes:*
- converting submit to BODS schema
- adding TS classes and objects to conform bods schema.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by kialj876 — COMMENTED** [review]
Just skimmed through for now, but its looking really good to me. Nice work

**Review by kialj876 — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-104-zzixxx9h.web.app

**Review by kialj876 — APPROVED** [review]
Looks good to me! I'll merge and build the api

**Pull request merged**
