### PR TITLE
20054 - Bump Nuxt to 3.10.3

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:20054 *https://github.com/bcgov/entity/issues/20054 

*Description of changes:*
Upgrading Nuxt version to 3.10.3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-137-eymk1wn3.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-137-eymk1wn3.web.app

**Review by kialj876 — APPROVED** [review]

**Pull request merged**
