### PR TITLE
UI/Schema: Update to conversion and country

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/19919

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by kialj876** [comment]
This looks good to me patrick - just needs the cypress tests updated

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-136-ggvyhptx.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-136-ggvyhptx.web.app

**Comment by patrickpeinanw** [comment]
> This looks good to me patrick - just needs the cypress tests updated

One test for Edit failed because it tried to update a SI fetched from db. The old address schema caused the error. I have updated the cypress test so that we test the edit feature with a newly added SI.

**Review by kialj876 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-136-ggvyhptx.web.app

**Pull request merged**
