### PR TITLE
19689 - Fixing color styles except gray.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:19689 *https://github.com/bcgov/entity/issues/19689 

*Description of changes:*
fixed all the tailwind colors except gray
created follow up ticket for dealing with gray color [ticket #19782](https://github.com/bcgov/entity/issues/19782)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-117-x7ztcgpb.web.app

**Review by kialj876 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-117-x7ztcgpb.web.app

**Pull request merged**
