### PR TITLE
20760 - date of significance section

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:20760 *https://github.com/bcgov/entity/issues/20760 

*Description of changes:*
- date of significance section
- component for date group start/end
- updated date select to have clearable icon
- updated tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-168-xpyav16l.web.app

**Review by kialj876 — APPROVED** [review]
Very nice work! 

Only thing I noticed is the hover state over the delete button highlights the whole row:
Screenshot 2024-05-30 at 10 29 37 AM

**Comment by hfekete** [comment]
> Very nice work!
> 
> Only thing I noticed is the hover state over the delete button highlights the whole row: Screenshot 2024-05-30 at 10 29 37 AM

Yeah, it will be doublechecked when goes UX verification if this is satisfying for them. There was a comment in the Figma (dev mode) to ask specifically for this.

**Pull request merged**
