### PR TITLE
In-concert Control of Shares and Votes

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/18727

*Description of changes:*
- Add the checkbox for "share or votes exercised in concert with other individuals"
- Fix the naming in "Control of Directors". (the field that was labeled as "noControl" should actually be "inConcertControl") 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-67-k9h1cqsr.web.app

**Comment by kialj876** [comment]
Test failure is my bad (when the date is xxxx-xx-0x utc it doesn't check for the padded 0) -- I'll fix that in my next PR

**Review by kialj876 — APPROVED** [review]
Nice work, lgtm 👍

**Review by hfekete — APPROVED** [review]

**Pull request merged**
