### PR TITLE
21604 - final SI changes

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:21604 *https://github.com/bcgov/entity/issues/21604 

*Description of changes:*
 - updating schema to track changed/new fields
 - updating bods transformer to add only fields that are edited/new
 - adding UI sugar allowing the redacted fields to clear input on focus
   - clear input on focus
   - revert to unedited value if no changes to the field

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by BrandonSharratt — CHANGES_REQUESTED** [review]
I haven't tested this due to the linting/test errors but overall this looks reasonable to me

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-193-gsgm0zyj.web.app

**Review by BrandonSharratt — CHANGES_REQUESTED** [review]
In testing the PR it appears to still be doing a POST when I was editing a user, and I appear to be unable to add a second user.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-193-gsgm0zyj.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-193-gsgm0zyj.web.app

**Comment by BrandonSharratt** [comment]
Looks good to me! Thanks for all the changes.

**Review by BrandonSharratt — APPROVED** [review]

**Pull request merged**
