### PR TITLE
20797 & 20799 - No Signigificant Individuals

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:20797*https://github.com/bcgov/entity/issues/20797
*Issue:20799*https://github.com/bcgov/entity/issues/20799

*Description of changes:*
No Signigificant Individuals changes for
- API 
- UI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-151-ha1slzxz.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-151-ha1slzxz.web.app

**Review by kialj876 — APPROVED** [review]
Looks good to me! Might want to verify the expanded help with julie before you merge though because I think this looks off with the 'hide help' where it is. That is how we do it for large help text that takes the whole screen and has its own sort of section, but for these small blurbs it looks a bit weird?

Screenshot 2024-04-24 at 10 31 02 AM

**Comment by hfekete** [comment]
> Looks good to me! Might want to verify the expanded help with julie before you merge though because I think this looks off with the 'hide help' where it is. That is how we do it for large help text that takes the whole screen and has its own sort of section, but for these small blurbs it looks a bit weird?
> 
> Screenshot 2024-04-24 at 10 31 02 AM

In designs I think they all look the same, but anyway will run it by Julie to see if she has any comments. 
Will pull these tickets in UX review also.

**Comment by hfekete** [comment]
Talked to Julie, there might be changes to the help component, but either way it will have same behavior no matter the size of the help text.

**Pull request merged**
