### PR TITLE
Fix some styles.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:*https://github.com/bcgov/entity/issues/

*Description of changes:*
Fixed some styling padding

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-146-am0fbmr4.web.app

**Review by kialj876 — APPROVED** [review]

**Review by patrickpeinanw — COMMENTED** [review]
Does the email section need a "pt-3" so the input box aligns with the "Email Address" label?

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-btr-dev--pr-146-am0fbmr4.web.app

**Pull request merged**
